[package]
name = "ouverture-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
structopt = "0.3"
log = "0.4"

ouverture-core = { path = "../ouverture-core"}

daemonize="0.5"
